# Generated by Django 5.2.16 on 2026-07-28 00:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', '초안'), ('ACTIVE', '진행 중'), ('ARCHIVED', '보관')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', '생성됨'), ('INGESTING', '문서 수집 중'), ('STRUCTURING', '지식 모델 생성 중'), ('SNAPSHOT_CREATED', '스냅샷 생성됨'), ('READINESS_CHECKED', '준비 상태 확인됨'), ('TASK_REVIEW_REQUIRED', 'PM 업무 확인 필요'), ('BLOCKED', '차단됨'), ('FAILED', '실패')], default='CREATED', max_length=40)),
                ('snapshot_as_of', models.DateTimeField(blank=True, null=True)),
                ('readiness_status', models.CharField(default='PENDING', max_length=30)),
                ('missing_data', models.JSONField(blank=True, default=list)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('assumptions', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(default='LOCAL', max_length=30)),
                ('source_file_id', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('declared_mime_type', models.CharField(blank=True, max_length=150)),
                ('detected_format', models.CharField(blank=True, max_length=50)),
                ('format_validation_status', models.CharField(default='UNKNOWN', max_length=20)),
                ('version', models.CharField(default='v1', max_length=100)),
                ('content_hash', models.CharField(blank=True, max_length=100)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('document_role', models.CharField(default='PROJECT_PLAN', max_length=50)),
                ('processing_status', models.CharField(default='PENDING', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
