# Generated by Django 5.2.16 on 2026-07-28 00:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rank_order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['rank_order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='people.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job_role', models.CharField(max_length=100)),
                ('employment_status', models.CharField(default='ACTIVE', max_length=30)),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=50)),
                ('fte', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('data_origin', models.CharField(default='SYNTHETIC', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_reports', to='people.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='people.organization')),
                ('responsibility_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.responsibilitylevel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence_type', models.CharField(max_length=30)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(default='APPROVED', max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekly_hours', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_type', models.CharField(max_length=30)),
                ('external_account_id', models.CharField(max_length=255)),
                ('external_email', models.EmailField(blank=True, max_length=254)),
                ('mapping_status', models.CharField(default='PENDING', max_length=30)),
                ('match_method', models.CharField(default='EMAIL', max_length=30)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('manual_override', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_links', to='people.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('system_type', 'external_account_id'), name='unique_external_identity')],
            },
        ),
        migrations.CreateModel(
            name='PersonSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency', models.PositiveSmallIntegerField(help_text='1~5')),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_skills', to='people.person')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'skill'), name='unique_person_skill')],
            },
        ),
    ]
